tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - PKief.material-icon-theme@4.0.1:uW65d0I1ibFxFDWPtc2zkQ==
    - dracula-theme.theme-dracula@2.21.0:RtzqaQieYebr5vxh8cZ+pQ==
    - burkeholland.simple-react-snippets@1.2.2:aB/gV0ExPn8v6vEZNUjoWA==
    - danielo515.danielo-node-snippets@1.8.1:thab5bnaRwL2VcE8ia7UoA==